/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState, type FormEvent } from "react";
import { Bell, Check, Settings, ShieldAlert, Users, Wallet } from "lucide-react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { usePrivy } from "@privy-io/react-auth";
import { useSessionHeaders } from "../lib/session";

type Notice = { tone: "info" | "success" | "error"; text: string };
type Props = { onNotice: (notice: Notice) => void };
function AdminShell({ children }: { children: React.ReactNode }) { const location = useLocation(); return <div className="admin-route"><aside className="admin-sidebar"><span className="eyebrow"><ShieldAlert size={13} /> CONTROL ROOM</span><h1>Operations<br /><em>without theatre.</em></h1><nav><Link className={location.pathname.endsWith("/bulletin") ? "active" : ""} to="/control-room/bulletin"><Bell size={15} /> Bulletin</Link><Link className={location.pathname.endsWith("/proposals") ? "active" : ""} to="/control-room/proposals"><Check size={15} /> Proposals</Link><Link className={location.pathname.endsWith("/members") ? "active" : ""} to="/control-room/members"><Users size={15} /> Members</Link><Link className={location.pathname.endsWith("/settings") ? "active" : ""} to="/control-room/settings"><Settings size={15} /> Settings</Link></nav></aside><main className="admin-route-main">{children}</main></div> }
async function adminRequest(action: string, payload: Record<string, unknown>, getHeaders: () => Promise<Record<string, string>>) { const headers = await getHeaders(); const response = await fetch(`/api/admin?action=${encodeURIComponent(action)}`, { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Admin action failed."); return body; }
export function AdminBulletinRoute({ onNotice }: Props) { const headers = useSessionHeaders(); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); try { setSaving(true); await adminRequest("protocol-announcement", { title, body }, headers); setTitle(""); setBody(""); onNotice({ tone: "success", text: "Bulletin published and email dispatch queued." }); } catch (error) { onNotice({ tone: "error", text: error instanceof Error ? error.message : "Bulletin failed." }); } finally { setSaving(false); } }; return <AdminShell><span className="eyebrow">PROTOCOL BULLETIN</span><h2>Send a signal<br /><em>to the whole network.</em></h2><form className="stack admin-form" onSubmit={submit}><label>Headline<input required value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Message<textarea required rows={8} value={body} onChange={(event) => setBody(event.target.value)} /></label><button className="primary-button" disabled={saving}>{saving ? "Dispatching…" : "Publish bulletin"} <Bell size={15} /></button></form></AdminShell> }
export function AdminProposalsRoute({ onNotice }: Props) { const headers = useSessionHeaders(); const [items, setItems] = useState<Array<{ _id?: string; proposalId?: string; title?: string; status?: string }>>([]); const [reference, setReference] = useState(""); const load = async () => { const auth = await headers(); const response = await fetch("/api/admin", { headers: auth }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setItems(body.proposals || []); }; useEffect(() => { void load().catch((error) => onNotice({ tone: "error", text: error.message })); }, []); const act = async (action: string, item: { _id?: string; proposalId?: string }, extra: Record<string, unknown> = {}) => { try { await adminRequest(action, { proposalId: item._id || item.proposalId, ...extra }, headers); await load(); onNotice({ tone: "success", text: "Control room action recorded." }); } catch (error) { onNotice({ tone: "error", text: error instanceof Error ? error.message : "Action failed." }); } }; return <AdminShell><span className="eyebrow">RESOLUTION DESK</span><h2>Ties and treasury<br /><em>need a human.</em></h2><div className="route-card-grid">{!items.length ? <p className="empty">No proposals need intervention.</p> : items.map((item) => <article className="route-card" key={item._id || item.proposalId}><span className="status status-2">{item.status}</span><h3>{item.title || "Untitled proposal"}</h3>{item.status === "tied" && <div className="admin-actions"><button className="primary-button" onClick={() => void act("resolve-tie", item, { support: true, reason: "Admin resolution" })}>Resolve yes</button><button className="ghost-button" onClick={() => void act("resolve-tie", item, { support: false, reason: "Admin resolution" })}>Resolve no</button></div>}{item.status === "manual_funding" && <div className="admin-actions"><input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Transfer hash/reference" /><button className="primary-button" onClick={() => void act("manual-funding", item, { reference })}>Record transfer</button></div>}</article>)}</div></AdminShell> }
export function AdminMembersRoute({ onNotice }: Props) { const headers = useSessionHeaders(); const [applications, setApplications] = useState<Array<{ _id: string; daoId: string; actor: string; reason?: string }>>([]); const load = async () => { const auth = await headers(); const response = await fetch("/api/admin", { headers: auth }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setApplications(body.applications || []); }; useEffect(() => { void load().catch((error) => onNotice({ tone: "error", text: error.message })); }, []); const decide = async (applicationId: string, approve: boolean) => { try { await adminRequest(approve ? "approve-membership" : "reject-membership", { applicationId }, headers); await load(); onNotice({ tone: "success", text: "Membership decision recorded." }); } catch (error) { onNotice({ tone: "error", text: error instanceof Error ? error.message : "Membership action failed." }); } }; return <AdminShell><span className="eyebrow">MEMBERS</span><h2>Moderate the<br /><em>human layer.</em></h2><p className="route-lede">Private membership approvals are authenticated server-side and recorded in the audit trail.</p><div className="route-card-grid">{!applications.length ? <p className="empty">No pending membership applications.</p> : applications.map((application) => <article className="route-card" key={application._id}><span className="status status-2">Pending</span><h3>{application.daoId}</h3><p>{application.reason || "No applicant note."}</p><small>{application.actor}</small><div className="admin-actions"><button className="primary-button" onClick={() => void decide(application._id, true)}>Approve</button><button className="ghost-button" onClick={() => void decide(application._id, false)}>Reject</button></div></article>)}</div></AdminShell> }
export function AdminSettingsRoute() { return <AdminShell><span className="eyebrow">SETTINGS</span><h2>Make the policy<br /><em>explicit.</em></h2><div className="route-grid"><article><Wallet size={20} /><h3>Treasury controls</h3><p>Weekly caps and manual funding thresholds are enforced before execution.</p></article><article><Settings size={20} /><h3>DAO metadata</h3><p>Mission, constitution, media, and discovery metadata are managed per DAO.</p></article></div></AdminShell> }
export function AdminDashboardRoute() { const navigate = useNavigate(); const { authenticated } = usePrivy(); return <AdminShell><span className="eyebrow">COMMAND CENTER</span><h2>Keep the network<br /><em>honest.</em></h2><p className="route-lede">Admin actions are split by responsibility so a bulletin cannot masquerade as a treasury operation.</p><div className="route-grid"><button className="route-card" onClick={() => navigate("/control-room/proposals")}>Resolution queue</button><button className="route-card" onClick={() => navigate("/control-room/bulletin")}>{authenticated ? "Publish bulletin" : "Sign in to publish"}</button></div></AdminShell> }
