import { useCallback, useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, Check, Settings, Shield, Users } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useSessionHeaders } from "../lib/session";

type Notice = { tone: "info" | "success" | "error"; text: string };
type Proposal = { _id?: string; proposalId?: string; title?: string; status?: string };
type Member = { actor?: string; wallet?: string; role?: string; status?: string };

export function DaoAdminRoute({ onNotice }: { onNotice: (notice: Notice) => void }) {
  const { daoId } = useParams();
  const headers = useSessionHeaders();
  const [data, setData] = useState<{ dao?: { name?: string; weeklyCap?: number; mission?: string; constitution?: string }; proposals?: Proposal[]; members?: Member[] }>({});
  const [cap, setCap] = useState("");
  const [reference, setReference] = useState("");
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { setLoading(true); const response = await fetch(`/api/dao-admin?daoId=${encodeURIComponent(daoId || "")}`, { headers: await headers() }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "DAO control room unavailable."); setData(body); setCap(String(body.dao?.weeklyCap || "")); } catch (error) { onNotice({ tone: "error", text: error instanceof Error ? error.message : "DAO control room unavailable." }); } finally { setLoading(false); } }, [daoId, headers, onNotice]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const action = async (payload: Record<string, unknown>) => { try { const response = await fetch(`/api/dao-admin?daoId=${encodeURIComponent(daoId || "")}&action=${encodeURIComponent(String(payload.action))}`, { method: "POST", headers: { ...(await headers()), "content-type": "application/json" }, body: JSON.stringify({ daoId, ...payload }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "DAO action failed."); onNotice({ tone: "success", text: "DAO control-room action recorded." }); await load(); } catch (error) { onNotice({ tone: "error", text: error instanceof Error ? error.message : "DAO action failed." }); } };
  const saveSettings = (event: FormEvent) => { event.preventDefault(); void action({ action: "settings", weeklyCap: cap }); };
  if (loading) return <div className="route-page"><span className="eyebrow">DAO CONTROL ROOM</span><h1>Loading controls…</h1></div>;
  return <div className="admin-route dao-admin-route"><aside className="admin-sidebar"><Link className="back-link" to={`/dao/${daoId}`}> <ArrowLeft size={15} /> {data.dao?.name || "DAO"}</Link><span className="eyebrow"><Shield size={13} /> DAO ADMIN</span><h1>Steward this<br /><em>covenant.</em></h1><nav><a href="#proposals">Proposals</a><a href="#members">Members</a><a href="#settings">Settings</a></nav></aside><main className="admin-route-main"><span className="eyebrow">DAO-SCOPED OPERATIONS</span><h2>{data.dao?.name || "DAO"}<br /><em>control room.</em></h2><p className="route-lede">These controls affect this DAO only. Protocol bulletins and platform monitoring live in the separate super-admin control room.</p><section id="proposals" className="route-section"><div className="detail-section-title"><Check size={16}/> Resolution queue</div><div className="route-card-grid">{data.proposals?.length ? data.proposals.map((item) => <article className="route-card" key={item._id || item.proposalId}><span className="status status-2">{item.status}</span><h3>{item.title || "Untitled proposal"}</h3>{item.status?.includes("tie") && <div className="admin-actions"><button className="primary-button" onClick={() => void action({ action: "resolve-tie", proposalId: item._id || item.proposalId, support: true })}>Resolve yes</button><button className="ghost-button" onClick={() => void action({ action: "resolve-tie", proposalId: item._id || item.proposalId, support: false })}>Resolve no</button></div>}{item.status?.includes("manual") && <div className="admin-actions"><input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Transfer reference"/><button className="primary-button" onClick={() => void action({ action: "manual-funding", proposalId: item._id || item.proposalId, reference })}>Record transfer</button></div>}</article>) : <p className="empty">No DAO proposals need intervention.</p>}</div></section><section id="members" className="route-section"><div className="detail-section-title"><Users size={16}/> Members · {data.members?.length || 0}</div><p className="route-lede">Membership moderation and role changes are scoped to this DAO. Platform user bans remain under protocol administration.</p></section><section id="settings" className="route-section"><div className="detail-section-title"><Settings size={16}/> Treasury parameters</div><form className="stack admin-form" onSubmit={saveSettings}><label>Weekly cap<input type="number" min="0" step="0.01" value={cap} onChange={(event) => setCap(event.target.value)} placeholder="0"/></label><button className="primary-button">Save DAO settings</button></form></section></main></div>;
}
