import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, NavLink, Navigate, Outlet, Route, Routes, useParams } from "react-router-dom";
import { formatUnits, type Address, type Abi } from "viem";
import { useSessionHeaders } from "../lib/session";
import { publicClient, walletClient } from "../lib/dao";
import daoArtifact from "../abi/DearmersDAO.json";
import { ProposalReview } from "../components/ProposalReview";
import type { Proposal } from "../../shared/proposals";

type Notice = { tone: "info" | "success" | "error"; text: string };
type Dao = { dao: string; name: string; description?: string; category?: string; tags?: string[]; mission?: string; constitution?: string; pendingMission?: string; pendingConstitution?: string; policySyncStatus?: string; policyError?: string };
type Member = { _id: string; actor: string; status: string; role?: string; reason?: string; profile?: Array<{ username?: string; displayName?: string }> };
type AdminData = { dao: Dao; proposals?: Proposal[]; members?: Member[]; applications?: Member[]; policy?: { version: string; constitution: Record<string, string | boolean>; threshold: string; admin: string }; events?: Array<{ _id: string; type: string; createdAt: string }>; delegation?: { status?: string; token?: string } };
function useDaoAdmin(view: string) {
  const { daoId = "" } = useParams(); const headers = useSessionHeaders();
  const [data, setData] = useState<AdminData | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const request = useCallback(async (payload?: Record<string, unknown>) => {
    const response = await fetch(`/api/dao-admin?daoId=${encodeURIComponent(daoId)}&view=${view}`, { headers: { ...(await headers()), "content-type": "application/json" }, ...(payload ? { method: "POST", body: JSON.stringify(payload) } : {}) });
    const body = await response.json(); if (!response.ok) throw new Error(body.error || "DAO control room unavailable."); return body;
  }, [daoId, view, headers]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData(await request()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Loading failed."); } finally { setLoading(false); } }, [request]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  return { daoId, headers, data, error, loading, load, request };
}
function Gate({ loading, error }: { loading: boolean; error: string }) { return <p className={error ? "notice error" : "empty"} role={error ? "alert" : "status"}>{error || (loading ? "Loading DAO controls…" : "DAO controls unavailable.")}</p>; }
function Layout() { const { daoId } = useParams(); return <div className="admin-route dao-admin-route"><aside className="admin-sidebar"><Link className="back-link" to={`/dao/${daoId}`}>← Back to DAO</Link><span className="eyebrow">DAO ADMINISTRATION</span><h1>Steward this<br /><em>covenant.</em></h1><nav aria-label="DAO administration">{["identity", "proposals", "members", "settings", "history"].map((name) => <NavLink key={name} to={`/dao/${daoId}/control-room/${name}`}>{name[0].toUpperCase() + name.slice(1)}</NavLink>)}</nav></aside><main className="admin-route-main"><Outlet /></main></div>; }
function Identity({ onNotice }: { onNotice: (notice: Notice) => void }) {
  const { data, loading, error, daoId, headers, request, load } = useDaoAdmin("identity"); const [busy, setBusy] = useState("");
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy("identity"); try { await request({ action: "update-identity", description: form.get("description"), category: form.get("category"), tags: String(form.get("tags") || "").split(","), mission: form.get("mission"), constitution: form.get("constitution") }); onNotice({ tone: "success", text: "Identity saved. Apply mission or constitution changes in Settings to make them effective." }); await load(); } catch (reason) { onNotice({ tone: "error", text: reason instanceof Error ? reason.message : "Save failed." }); } finally { setBusy(""); } };
  const upload = async (file: File, purpose: string) => {
    setBusy(purpose);
    try {
      if (file.size > 3_000_000) throw new Error("Use an image smaller than 3 MB.");
      const encoded = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1]); reader.onerror = () => reject(new Error("Could not read image.")); reader.readAsDataURL(file); });
      const response = await fetch("/api/media", { method: "POST", headers: { ...(await headers()), "content-type": "application/json" }, body: JSON.stringify({ fileName: file.name, mimeType: file.type, data: encoded, scope: "dao", resourceId: daoId, purpose }) });
      const body = await response.json(); if (!response.ok) throw new Error(body.error || "Image upload failed.");
      await request({ action: "update-media", [purpose === "dao-logo" ? "logoUri" : "bannerUri"]: body.url }); onNotice({ tone: "success", text: "DAO image updated." }); await load();
    } catch (reason) { onNotice({ tone: "error", text: reason instanceof Error ? reason.message : "Upload failed." }); }
    finally { setBusy(""); }
  };
  if (!data) return <Gate loading={loading} error={error} />;
  const dao = data.dao;
  return <><h2>{dao.name} · Identity</h2>{(dao.pendingConstitution || dao.pendingMission) && <p className="notice">Policy edits are saved as drafts. <Link to={`../settings`}>Apply them in Settings →</Link></p>}<form className="stack admin-form" onSubmit={save} key={`${dao.description}:${dao.pendingMission}:${dao.pendingConstitution}`}><label>Description<textarea name="description" defaultValue={dao.description} maxLength={2000} /></label><label>Mission<textarea name="mission" defaultValue={dao.pendingMission || dao.mission} maxLength={5000} required /></label><label>Constitution<textarea name="constitution" defaultValue={dao.pendingConstitution || dao.constitution} maxLength={15000} rows={8} required /></label><label>Category<input name="category" defaultValue={dao.category} maxLength={80} /></label><label>Discovery tags <small>comma-separated</small><input name="tags" defaultValue={dao.tags?.join(", ")} /></label><button className="primary-button" disabled={Boolean(busy)}>{busy === "identity" ? "Saving…" : "Save identity"}</button></form><section className="route-section"><h3>DAO media</h3><div className="admin-actions">{["dao-logo", "dao-banner"].map((purpose) => <label className="media-field" key={purpose}>{purpose === "dao-logo" ? "Logo" : "Banner"}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={Boolean(busy)} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file, purpose); event.target.value = ""; }} /></label>)}</div></section></>;
}
function ProposalQueue({ onNotice }: { onNotice: (notice: Notice) => void }) {
  const { daoId, data, loading, error, request, load } = useDaoAdmin("proposals"); const [filter, setFilter] = useState("all"); const [selected, setSelected] = useState(""); const [busy, setBusy] = useState("");
  const resolve = async (proposal: Proposal, support: boolean) => {
    setBusy(proposal._id);
    try {
      if (proposal.onchainProposalId === undefined || !proposal.daoAddress) throw new Error("The onchain proposal record is unavailable.");
      const wallet = await walletClient(); const hash = await wallet.writeContract({ address: proposal.daoAddress as Address, abi: daoArtifact.abi as Abi, functionName: "resolveTiedProposal", args: [BigInt(proposal.onchainProposalId), support] });
      const receipt = await publicClient.waitForTransactionReceipt({ hash }); if (receipt.status !== "success") throw new Error("Tie resolution reverted.");
      await request({ action: "sync-governance", proposalId: proposal._id }); await load(); onNotice({ tone: "success", text: "Tie resolution confirmed onchain." });
    } catch (reason) { onNotice({ tone: "error", text: reason instanceof Error ? reason.message : "Resolution failed." }); }
    finally { setBusy(""); }
  };
  if (!data) return <Gate loading={loading} error={error} />;
  const items = (data.proposals || []).filter((proposal) => filter === "all" || (filter === "review" ? ["awaiting_ai_review", "evaluating", "approved_for_voting"].includes(proposal.status) : proposal.status === filter));
  return <><h2>Proposal operations</h2><label className="filter-field">Show<select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All proposals</option><option value="review">AI review and recovery</option><option value="active_voting">Member voting</option><option value="tied">Tied votes</option><option value="manual_funding">Manual funding</option></select></label>{!items.length && <p className="empty">No proposals in this view.</p>}{items.map((proposal) => <article className="route-section" key={proposal._id}><span className="status">{proposal.status.replaceAll("_", " ")}</span><h3><Link to={`/dao/${daoId}/proposals/${proposal._id}`}>{proposal.title}</Link></h3><div className="admin-actions"><button className="ghost-button" onClick={() => setSelected(selected === proposal._id ? "" : proposal._id)}>{selected === proposal._id ? "Hide review" : "AI Review"}</button>{proposal.status === "tied" && <><button className="primary-button" disabled={Boolean(busy)} onClick={() => void resolve(proposal, true)}>Resolve yes</button><button className="ghost-button" disabled={Boolean(busy)} onClick={() => void resolve(proposal, false)}>Resolve no</button></>}</div>{selected === proposal._id && <ProposalReview daoId={daoId} proposalId={proposal._id} />}{proposal.status === "manual_funding" && <ManualFunding proposal={proposal} onNotice={onNotice} onComplete={load} />}</article>)}</>;
}
function ManualFunding({ proposal, onNotice, onComplete }: { proposal: Proposal; onNotice: (notice: Notice) => void; onComplete: () => Promise<void> }) {
  const headers = useSessionHeaders(); const [reference, setReference] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { const response = await fetch("/api/manual-funding", { method: "POST", headers: { ...(await headers()), "content-type": "application/json" }, body: JSON.stringify({ daoId: proposal.daoId, proposalId: proposal._id, hash: reference }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Transfer verification failed."); const wallet = await walletClient(); const hash = await wallet.writeContract({ address: proposal.daoAddress as Address, abi: daoArtifact.abi as Abi, functionName: "recordManualFunding", args: [BigInt(proposal.onchainProposalId!), reference] }); const receipt = await publicClient.waitForTransactionReceipt({ hash }); if (receipt.status !== "success") throw new Error("Funding record reverted."); await onComplete(); onNotice({ tone: "success", text: "Verified manual funding recorded onchain." }); } catch (reason) { onNotice({ tone: "error", text: reason instanceof Error ? reason.message : "Manual funding failed." }); } finally { setBusy(false); } };
  return <form className="stack" onSubmit={submit}><p>Transfer the approved amount from this DAO’s treasury, then verify the receipt. This form does not send funds.</p><label>Base USDC transfer hash<input value={reference} onChange={(event) => setReference(event.target.value)} pattern="0x[a-fA-F0-9]{64}" required placeholder="0x…" /></label><button className="ghost-button" disabled={busy}>{busy ? "Verifying…" : "Verify and record transfer"}</button></form>;
}
function Members({ onNotice }: { onNotice: (notice: Notice) => void }) {
  const { daoId, headers, data, loading, error, load } = useDaoAdmin("members"); const [busy, setBusy] = useState("");
  const decide = async (applicationId: string, decision: string) => { setBusy(applicationId); try { const response = await fetch("/api/members", { method: "POST", headers: { ...(await headers()), "content-type": "application/json" }, body: JSON.stringify({ daoId, applicationId, decision }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Membership decision failed."); await load(); onNotice({ tone: "success", text: `Membership ${decision === "approve" ? "approved" : "rejected"}.` }); } catch (reason) { onNotice({ tone: "error", text: reason instanceof Error ? reason.message : "Membership update failed." }); } finally { setBusy(""); } };
  if (!data) return <Gate loading={loading} error={error} />;
  return <><h2>Members and applications</h2><section className="route-section"><h3>Pending applications</h3>{!data.applications?.length && <p className="empty">No pending membership requests.</p>}{data.applications?.map((member) => <article className="admin-log-row" key={member._id}><p>{member.reason || "No application note."}</p><div className="admin-actions"><button className="primary-button" disabled={Boolean(busy)} onClick={() => void decide(member._id, "approve")}>Approve</button><button className="ghost-button" disabled={Boolean(busy)} onClick={() => void decide(member._id, "reject")}>Reject</button></div></article>)}</section><section className="route-section"><h3>Members · {data.members?.length || 0}</h3>{data.members?.map((member) => <article className="admin-log-row" key={member._id}><strong>{member.profile?.[0]?.displayName || member.profile?.[0]?.username || "DAO member"}</strong><span>{member.role || "member"} · {member.status}</span></article>)}</section></>;
}
function Settings({ onNotice }: { onNotice: (notice: Notice) => void }) {
  const { data, loading, error, request, load } = useDaoAdmin("settings"); const [busy, setBusy] = useState("");
  const sync = async () => { setBusy("sync"); try { await request({ action: "sync-policy" }); await load(); onNotice({ tone: "info", text: "Policy synchronization checked. Pending GenLayer transactions must finalize before review starts." }); } catch (reason) { onNotice({ tone: "error", text: reason instanceof Error ? reason.message : "Synchronization failed." }); } finally { setBusy(""); } };
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy("save");
    try {
      const prepared = await request({ action: "prepare-policy", weeklyLimit: form.get("weeklyLimit"), maxProposalAmount: form.get("maxProposalAmount"), manualFundingThreshold: form.get("manualFundingThreshold") });
      const wallet = await walletClient(); if (wallet.account?.address.toLowerCase() !== prepared.admin.toLowerCase()) throw new Error("Connect this DAO's onchain administrator wallet.");
      const policy = { ...prepared.policy }; for (const field of ["version", "activatesAt", "votingPeriod", "maxProposalAmount", "weeklySpendLimit", "quorumBps", "approvalBps", "participationWeightCap", "tokenWeightCap", "gateBalance", "tokenWeightUnit"]) policy[field] = BigInt(policy[field]);
      const hash = await wallet.writeContract({ address: prepared.address, abi: daoArtifact.abi as Abi, functionName: "configurePolicy", args: [policy, BigInt(prepared.threshold)] });
      const receipt = await publicClient.waitForTransactionReceipt({ hash }); if (receipt.status !== "success") throw new Error("Policy transaction reverted.");
      await request({ action: "sync-policy" }); await load(); onNotice({ tone: "success", text: "Onchain policy updated. GenLayer synchronization is pending finality." });
    } catch (reason) { onNotice({ tone: "error", text: reason instanceof Error ? reason.message : "Policy update failed." }); }
    finally { setBusy(""); }
  };
  if (!data?.policy) return <Gate loading={loading} error={error} />;
  const units = (value: unknown) => formatUnits(BigInt(String(value || "0")), 6);
  return <><h2>Treasury and governance policy</h2><p className="route-lede">Limits below are read from the DAO contract. Saving requires the DAO admin wallet and an onchain confirmation.</p><p className="notice">Constitution v{data.policy.version} · GenLayer {data.dao.policySyncStatus || "setup required"}{data.dao.policyError && ` · ${data.dao.policyError}`}</p><form className="stack admin-form" onSubmit={submit} key={data.policy.version}><label>Weekly spending cap · USDC<input name="weeklyLimit" type="number" min="0" step="0.000001" required defaultValue={units(data.policy.constitution.weeklySpendLimit)} /></label><label>Maximum proposal amount · USDC<input name="maxProposalAmount" type="number" min="0" step="0.000001" required defaultValue={units(data.policy.constitution.maxProposalAmount)} /></label><label>Automatic funding threshold · USDC<input name="manualFundingThreshold" type="number" min="0" step="0.000001" required defaultValue={units(data.policy.threshold)} /><small>Larger approved requests require verified manual funding.</small></label><p>Voting period: 72 hours. Mission/constitution drafts from Identity are included when applying policy.</p><button className="primary-button" disabled={Boolean(busy)}>{busy === "save" ? "Waiting for confirmation…" : "Apply onchain policy"}</button></form><button className="ghost-button" disabled={Boolean(busy)} onClick={() => void sync()}>{busy === "sync" ? "Checking…" : "Sync GenLayer policy"}</button><section className="route-section"><h3>Treasury delegation</h3><p>{data.delegation ? `${data.delegation.status || "Stored"} · ${data.delegation.token || "USDC"}` : "No treasury delegation recorded. Automated payments require a valid DAO-scoped delegation."}</p></section></>;
}
function History() { const { data, loading, error } = useDaoAdmin("history"); if (!data) return <Gate loading={loading} error={error} />; return <><h2>DAO audit history</h2>{!data.events?.length && <p className="empty">No DAO actions recorded.</p>}{data.events?.map((event) => <article className="admin-log-row" key={event._id}><strong>{event.type.replaceAll("_", " ")}</strong><time>{new Date(event.createdAt).toLocaleString()}</time></article>)}</>; }

export function DaoAdminRoute({ onNotice }: { onNotice: (notice: Notice) => void }) { return <Routes><Route element={<Layout />}><Route index element={<Navigate to="identity" replace />} /><Route path="identity" element={<Identity onNotice={onNotice} />} /><Route path="proposals" element={<ProposalQueue onNotice={onNotice} />} /><Route path="members" element={<Members onNotice={onNotice} />} /><Route path="settings" element={<Settings onNotice={onNotice} />} /><Route path="history" element={<History />} /><Route path="*" element={<Navigate to="identity" replace />} /></Route></Routes>; }
