import { useMemo, useState } from "react";
import { ArrowUpRight, Compass, Filter, Search, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import type { DaoRecord } from "../lib/dao";

export function ExplorerPage({ daos }: { daos: DaoRecord[] }) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const visible = useMemo(() => daos.filter((dao) => {
    const text = `${dao.name} ${dao.description || ""} ${dao.category || ""} ${(dao.tags || []).join(" ")}`.toLowerCase();
    return (!query || text.includes(query.toLowerCase())) && (filter === "all" || (filter === "grants" ? dao.mode === 1 : dao.mode === 0));
  }).sort((a, b) => Number(b.mode) - Number(a.mode)), [daos, filter, query]);
  const featured = visible[0];
  return <div className="explorer-page"><div className="explorer-hero"><div className="explorer-hero-copy"><span className="eyebrow"><Compass size={13}/> THE SANCTUARY INDEX</span><h2>Find the communities<br /><em>already in motion.</em></h2><p>Explore autonomous organisations with public constitutions, bounded treasuries, and evidence-led decision loops.</p><div className="explorer-stats"><span><strong>{daos.length}</strong> covenants indexed</span><span><strong>{daos.filter((dao) => dao.mode === 1).length}</strong> grant assemblies</span></div></div>{featured ? <Link className="featured-dao" to={`/dao/${featured.daoId}`} style={{ backgroundImage: `linear-gradient(90deg, rgba(5,5,5,.92), rgba(5,5,5,.2)), url(${featured.bannerUri || "/hero.png"})` }}><span className="featured-kicker"><Sparkles size={13}/> FEATURED COVENANT</span><div><strong>{featured.name}</strong><p>{featured.description || featured.mission || "A sovereign organisation building in public."}</p></div><ArrowUpRight size={20}/></Link> : <div className="featured-dao empty-feature"><span>NO COVENANTS YET</span><strong>Forge the first sanctuary.</strong><Link to="/forge">Begin inception <ArrowUpRight size={15}/></Link></div>}</div><div className="explorer-toolbar"><label className="search-field"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search names, missions, categories…" /></label><div className="filter-tabs"><Filter size={14}/>{[["all", "All covenants"], ["grants", "Grant assemblies"], ["operating", "Operating DAOs"]].map(([value, label]) => <button key={value} className={filter === value ? "active" : ""} onClick={() => setFilter(value)}>{label}</button>)}</div></div><section className="explorer-grid">{visible.map((dao) => <Link className="dao-explorer-card" key={dao.daoId} to={`/dao/${dao.daoId}`}><div className="dao-card-image" style={{ backgroundImage: `url(${dao.bannerUri || "/hero.png"})` }}><span>{dao.mode === 1 ? "GRANT DAO" : "OPERATING DAO"}</span>{dao.logoUri && <img src={dao.logoUri} alt="" loading="lazy" />}</div><div className="dao-card-copy"><div><span className="card-category">{dao.category || "Sovereign organisation"}</span><h3>{dao.name}</h3></div><ArrowUpRight size={17}/><p>{dao.description || dao.mission || "Constitution-led coordination with an autonomous review layer."}</p><footer><span>{dao.access || "public"}</span><span>{dao.gateStandard || "open access"}</span></footer></div></Link>)}{!visible.length && <div className="explorer-empty"><Sparkles size={24}/><strong>No covenants match that signal.</strong><span>Try another search or forge a new organisation.</span></div>}</section></div>;
}
