import { useCallback, useEffect, useState } from "react";
import { Bell, CheckCheck, ExternalLink } from "lucide-react";
import type { Address } from "viem";
import { useSessionHeaders } from "../lib/session";

type Notification = { _id?: string; kind?: string; title: string; body: string; daoId?: string; createdAt: string; readAt?: string | null };
export function NotificationsPage({ account, onNotice }: { account: Address | ""; onNotice: (notice: { tone: "info" | "success" | "error"; text: string }) => void }) {
  const sessionHeaders = useSessionHeaders();
  const [items, setItems] = useState<Notification[]>([]); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { if (!account) return; try { setLoading(true); const headers = await sessionHeaders(); const response = await fetch(`/api/notifications?wallet=${account}`, { headers }); const body = await response.json() as { notifications?: Notification[]; error?: string }; if (!response.ok) throw new Error(body.error || "Notifications unavailable."); setItems(body.notifications || []); } catch (error) { onNotice({ tone: "error", text: error instanceof Error ? error.message : "Notifications unavailable." }); } finally { setLoading(false); } }, [account, onNotice, sessionHeaders]);
  useEffect(() => { if (!account) return; const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [account, load]);
  const markRead = async () => { if (!account) return; const headers = await sessionHeaders(); await fetch("/api/notifications", { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ wallet: account }) }); setItems((current) => current.map((item) => ({ ...item, readAt: new Date().toISOString() }))); };
  if (!account) return <div className="notification-page"><div className="select-state"><Bell size={32}/><h3>Enter the sanctuary to see signals.</h3><p>Connect your wallet from any workspace to load private notifications.</p></div></div>;
  return <div className="notification-page"><div className="notification-heading"><span className="eyebrow"><Bell size={13}/> SIGNALS</span><h2>What moved<br /><em>while you were away.</em></h2><div><button className="ghost-button" onClick={() => void load()} disabled={loading}>Refresh</button><button className="primary-button" onClick={() => void markRead()}><CheckCheck size={15}/> Mark all read</button></div></div><section className="notification-list">{items.length ? items.map((item, index) => <article className={item.readAt ? "read" : ""} key={item._id || `${item.title}-${index}`}><span className="notification-mark"><Bell size={15}/></span><div><small>{new Date(item.createdAt).toLocaleString()}</small><h3>{item.title}</h3><p>{item.body}</p>{item.daoId && <a href={`/dao/${item.daoId}`}>Open covenant <ExternalLink size={13}/></a>}</div></article>) : <div className="notification-empty"><Bell size={22}/><strong>No new signals.</strong><span>Follow a covenant to receive its announcements and governance activity.</span></div>}</section></div>;
}
