import { useState } from "react";
import { Activity, Ban, Megaphone, ShieldAlert, Wallet } from "lucide-react";
import type { Address } from "viem";
import { walletClient } from "../lib/dao";

type Notice = { tone: "info" | "success" | "error"; text: string };
export function ProtocolAdminPage({ account, onNotice }: { account: Address | ""; onNotice: (notice: Notice) => void }) {
  const [target, setTarget] = useState(""); const [kind, setKind] = useState<"ban-user" | "ban-dao">("ban-dao"); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [loading, setLoading] = useState(false); const [overview, setOverview] = useState<{ users?: unknown[]; daos?: unknown[] } | null>(null);
  const request = async (action: string, payload: Record<string, unknown> = {}) => { if (!account) throw new Error("Connect an allowlisted protocol wallet."); const client = await walletClient(); const signature = await client.signMessage({ account: client.account!, message: `Dearmers-Dao\nAction: admin:${action}\nWallet: ${account.toLowerCase()}\nResource: ${action}` }); const response = await fetch("/api/admin", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...payload, wallet: account, signature, action }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "Protocol action failed."); };
  const run = async (action: string, payload?: Record<string, unknown>) => { try { setLoading(true); await request(action, payload); onNotice({ tone: "success", text: `${action} completed.` }); } catch (error) { onNotice({ tone: "error", text: error instanceof Error ? error.message : "Protocol action failed." }); } finally { setLoading(false); } };
  const inspect = async () => { try { setLoading(true); if (!account) throw new Error("Connect an allowlisted protocol wallet."); const client = await walletClient(); const signature = await client.signMessage({ account: client.account!, message: `Dearmers-Dao\nAction: admin:overview\nWallet: ${account.toLowerCase()}\nResource: overview` }); const response = await fetch(`/api/admin?action=overview&wallet=${account}&signature=${encodeURIComponent(signature)}`); const result = await response.json() as { error?: string; users?: unknown[]; daos?: unknown[] }; if (!response.ok) throw new Error(result.error || "Could not load overview."); setOverview(result); } catch (error) { onNotice({ tone: "error", text: error instanceof Error ? error.message : "Could not load overview." }); } finally { setLoading(false); } };
  return <div className="admin-page"><div className="admin-heading"><span className="eyebrow"><ShieldAlert size={13}/> RESTRICTED SURFACE</span><h2>Protocol<br /><em>control room.</em></h2><p>Moderate discovery and network communication without mutating autonomous DAO treasury contracts.</p></div><div className="admin-grid"><section className="admin-panel"><div className="detail-section-title"><Activity size={16}/> Operational overview</div><button className="primary-button" onClick={() => void inspect()} disabled={loading}><Wallet size={15}/> Load signed overview</button>{overview && <div className="admin-metrics"><strong>{overview.daos?.length || 0}<small> indexed covenants</small></strong><strong>{overview.users?.length || 0}<small> known profiles</small></strong></div>}</section><section className="admin-panel"><div className="detail-section-title"><Ban size={16}/> Discovery moderation</div><select value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="ban-dao">DAO</option><option value="ban-user">User</option></select><input value={target} onChange={(event) => setTarget(event.target.value)} placeholder={kind === "ban-dao" ? "DAO id" : "Wallet address"}/><div className="admin-actions"><button className="ghost-button" onClick={() => void run(kind, { target, banned: true })} disabled={loading || !target}>Hide from discovery</button><button className="ghost-button" onClick={() => void run(kind, { target, banned: false })} disabled={loading || !target}>Restore visibility</button></div></section><section className="admin-panel admin-announcement"><div className="detail-section-title"><Megaphone size={16}/> Protocol bulletin</div><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Bulletin title"/><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="A platform-wide message…" rows={5}/><button className="primary-button" onClick={() => void run("protocol-announcement", { title, body })} disabled={loading || !title || !body}>Publish bulletin</button></section></div></div>;
}
